name: healthup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.1.1
  cloud_firestore: 5.0.2
  firebase_auth: 5.1.1
  firebase_storage: 12.1.0
  table_calendar: ^3.1.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ic_launcher.png
    - assets/aguacount.png
    - assets/caloriascount.png
    - assets/perfil.png
